lwcproject/PHOTOS/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.main , name = 'main'),
    path('<int:id>', views.info , name = 'info'),
    path('search', views.search , name = 'search'),
    path('<str:category>' , views.categories , name='categories')
]

lwcproject/lwcproject/urls.py
from django.contrib import admin
from django.urls import path , include
from .settings import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('PHOTOS.urls')),
]
urlpatterns += static(STATIC_URL,document_root = STATIC_ROOT)+ static(MEDIA_URL,document_root = MEDIA_ROOT)

lwcproject/PHOTOS/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    Category = models.CharField(max_length=100)

    def __str__(self):
        return self.Category

class Photos(models.Model):

    category = models.ForeignKey(Category , on_delete=models.CASCADE)
    Image = models.ImageField(null = True)
    Title = models.CharField(max_length=100)
    Description = models.TextField(max_length=1000)
    @property

    def imageURL(self):
        try:
            return self.Image.url
        except:
            return ''

    def __str__(self) :
        return self.Title

lwcproject/PHOTOS/forms.py
from django import forms

class Search(forms.Form):
    search = forms.CharField(label='', max_length=200 , widget=forms.TextInput(attrs={'class': 'search-box' , 'placeholder':'search'}))

lwcproject/PHOTOS/views.py
from typing import Text
from django.shortcuts import render
from .forms import Search
from .models import  Category , Photos
# Create your views here.

def main(response):
    ls = Category.objects.all()
    form = Search()
    return render(response , 'PHOTOS/index.html' , {'ls':ls,'form':form})

def categories(response , category):
    ls = Category.objects.all()
    form = Search()
    return render(response , 'PHOTOS/categories.html' , {'ls':ls , 'form':form , 'category':category})

def info(response , id):
    ls = Category.objects.all()
    contex = {
        'ls':ls,
        'id':id
    }
    return render(response , 'PHOTOS/info.html' , contex)

def search(response):
    text = ''
    if response.method=="POST":
        form = Search(response.POST)
        if form.is_valid():
            text = response.POST.get('search')
        else:
            print('invalid')
    T = Photos.objects.filter(Title__icontains = text)
    return render(response , 'PHOTOS/search.html' , {'text':text,'T':T})

lwcproject/PHOTOS/templates/PHOTOS/cars.html
{% extends 'PHOTOS/layout.html' %}

{% block title %}
Main Page
{% endblock %}

{% block header %}
    <li><a href="/cars">Cars</a></li>
    <li><a href="/books">Books</a></li>
    <li><a href="/design">Design</a></li>
    <li><a href="/code">Code</a></li>
{% endblock %}

{% block serach %}
<form action="/search" method="post" class="din form-search" >
    {% csrf_token %}
    {{form}}
    <!-- <input class="search-box" type="text" name="search" placeholder="serach"> -->
    <button class='search-button' type="submit" name="send">Search</button>
</form>
{% endblock %}

{% block body %}

    <div class="container-content">
        {% for item in ls %}
            {% if item.Category == 'Car' %}
                {% for items in item.photos_set.all %}
                    <div class="content">
                        <div class="image">
                            <img class="image1" src="{{ items.imageURL }}" alt="mustbe_image">
                        </div>
                        <p class="name">Pick name: {{ items.Title }}</p>
                        <p>Category: {{ items.category }}</p>
                        <form action="{{items.id}}" method="GET">
                            {% csrf_token %}
                            <button class='btn' type="submit" name="{{items.id}}">View</button>
                        </form>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

lwcproject/PHOTOS/templates/PHOTOS/categories.html
{% extends 'PHOTOS/layout.html' %}

{% block title %}
Categories
{% endblock %}

{% block header %}
{% for item in ls %}
<li> <a href="/{{item.Category}}">{{item.Category}}</a></li>
{% endfor %}
{% endblock %}

{% block serach%}
<form action="/search" method="post" class="din form-search" >
    {% csrf_token %}
    {{form}}
    <button class='search-button' type="submit" name="search">Search</button>
</form>
{% endblock %}

{% block body %}
    <div class="container-content">
        {% for item in ls %}
            {% if item.Category == category %}
                {% for items in item.photos_set.all %}
                    <div class="content">
                        <div class="image">
                            <img class="image1" src="{{ items.imageURL }}" alt="mustbe_image">
                        </div>
                        <p class="name">Pick name: {{ items.Title }}</p>
                        <p>Category: {{ items.category }}</p>
                        <form action="/{{items.id}}" method="GET">
                            {% csrf_token %}
                            <button class='btn' type="submit" name="{{items.id}}">View</button>
                        </form>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

lwcproject/PHOTOS/templates/PHOTOS/index.html
{% extends 'PHOTOS/layout.html' %}

{% block title %}
Main Page
{% endblock %}

{% block header %}
    {% for item in ls %}
    <li> <a href="/{{item.Category}}">{{item.Category}}</a></li>
    {% endfor %}
{% endblock %}

{% block serach%}
<form action="/search" method="post" class="din form-search" >
    {% csrf_token %}
    {{form}}
    <button class='search-button' type="submit" name="send">Search</button>
</form>
{% endblock %}

{% block body %}

    <div class="container-content">
        {% for item in ls %}
            {% for items in item.photos_set.all %}
            <div class="content">
                <div class="image">
                    <img class="image1" src="{{ items.imageURL }}" alt="mustbe_image">
                </div>
                <p class="name">Pick name: {{ items.Title }}</p>
                <p>Category: {{ items.category }}</p>
                <form action="{{items.id}}" method="GET">
                    {% csrf_token %}
                    <button class='btn' type="submit" name="{{items.id}}">View</button>
                </form>
            </div>
            {% endfor %}
        {% endfor %}
    </div>

{% endblock %}

lwcproject/PHOTOS/templates/PHOTOS/info.html
{% extends 'PHOTOS/layout.html' %}

{% block title %}
Information page
{% endblock %}

{% block body %}

<div class="container-content">
    {% for item in ls %}
        {% for items in item.photos_set.all %}
            {% if items.id == id %}
                <h2 class="title">Pick name: {{ items.Title }}</h2>
                    <div class="content-box">
                        <div class="image-box">
                            <img class="image1-view" src="{{ items.imageURL }}" alt="mustbe_image">
                        </div>
                        <p>Category: {{ items.category }}</p>
                        <p>Description: {{ items.Description }}</p>
                    </div>
                    {% endif %}
                {% endfor %}
        {% endfor %}
    </div>

{% endblock %}

lwcproject/PHOTOS/templates/PHOTOS/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href='{% static "PHOTOS/main.css" %}?{% now "U" %}'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Base {% endblock %} </title>
</head>
<body>
    <div class="container">
          
        <div class="header"> 
            <ul class="din">
                <li><h3>Album</h3></li>
                <li><a href="/">All</a></li>
                {% block header %}
                

                {% endblock %}
            </ul>
                
                {% block serach%}

                {% endblock %}
        </div>

        

        

        <div class='blockbody'>
            {% block body %}
            
            {% endblock %}
        </div>

            {% block footer%}
            
            {% endblock %}

</body>
</html>

lwcproject/PHOTOS/templates/PHOTOS/search.html
{% extends 'PHOTOS/layout.html' %}

{% block title %}
Search page
{% endblock %}

{% block body %}

<div class="container-content">
    {% if T %}
    {% for item in T %}
        <h2 class="title">Pick name: {{ item.Title }}</h2>
            <div class="content-box">
                <div class="image-box">
                    <img class="image1-view" src="{{ item.imageURL }}" alt="mustbe_image">
                </div>
                <p>Category: {{ item.category }}</p>
                <p>Description: {{ item.Description }}</p>
            </div> 
    {% endfor %}
    {% else %}
    <h2 class="title">Qidiruv bo'yicha ma'lumot topilmadi</h2>
    {% endif %}
    </div>

{% endblock %}